extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_segment2_11C58_rgba16_rgba16[];
extern u8 castle_grounds_dl_jrb_textures_0B800_rgba16_rgba16[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[525];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_001_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_001_mesh_layer_5_vtx_0[52];
extern Gfx castle_grounds_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_4_vtx_cull[8];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_4_vtx_0[32];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_4_tri_0[];
extern Gfx mat_castle_grounds_dl_sm64_material_001[];
extern Gfx mat_revert_castle_grounds_dl_sm64_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_layer5[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_layer5[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001_layer4_area1[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001_layer4_area1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_001_mesh_layer_5[];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_4[];
