extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const MacroObject bits_area_1_macro_objs[];
extern u8 bits_dl_RMGP01_f7fc1e5f_14_ci4[];
extern u8 bits_dl_RMGP01_f7fc1e5f_14_pal_rgba16[];
extern u8 bits_dl_Texture0103_RGB_ci4[];
extern u8 bits_dl_Texture0103_RGB_pal_rgba16[];
extern Vtx bits_dl_1stPillar_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_1stPillar_mesh_layer_1_vtx_0[88];
extern Gfx bits_dl_1stPillar_mesh_layer_1_tri_0[];
extern Vtx bits_dl_1stPillar_mesh_layer_1_vtx_1[8];
extern Gfx bits_dl_1stPillar_mesh_layer_1_tri_1[];
extern Vtx bits_dl_DeathPlane_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_DeathPlane_mesh_layer_1_vtx_0[4];
extern Gfx bits_dl_DeathPlane_mesh_layer_1_tri_0[];
extern Gfx mat_bits_dl_pillar[];
extern Gfx mat_revert_bits_dl_pillar[];
extern Gfx mat_bits_dl_carpet[];
extern Gfx mat_revert_bits_dl_carpet[];
extern Gfx mat_bits_dl_death_plane[];
extern Gfx mat_revert_bits_dl_death_plane[];
extern Gfx bits_dl_1stPillar_mesh_layer_1[];
extern Gfx bits_dl_DeathPlane_mesh_layer_1[];
