extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_bob_textures_05800_rgba16_i8[];
extern u8 bob_dl_bob_textures_09000_rgba16_i8[];
extern u8 bob_dl_segment2_11C58_rgba16_ia16[];
extern u8 bob_dl_segment2_11C58_rgba16_i8[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[67];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[230];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_001_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Plane_001_mesh_layer_5_vtx_0[20];
extern Gfx bob_dl_Plane_001_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_0[96];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_sm64_material_001[];
extern Gfx mat_revert_bob_dl_sm64_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_001_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001_layer1_area1[];
extern Gfx mat_bob_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_bob_dl_f3dlite_material_layer5_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_layer5_area1[];
extern Gfx mat_bob_dl_f3dlite_material_003_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003_layer1_area1[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_5[];
extern Gfx bob_dl_Plane_002_mesh_layer_1[];
